const ADD_MODEL = 'ADD_MODEL'
const ADD_ENGINE = 'ADD_ENGINE'
const ADD_GEARBOX = 'ADD_GEARBOX'
const ADD_COLOR = 'ADD_COLOR'

const REMOVE_UNDER_MODEL = 'REMOVE_UNDER_MODEL'
const REMOVE_UNDER_ENGINE = 'REMOVE_UNDER_ENGINE'
const REMOVE_UNDER_GEARBOX = 'REMOVE_UNDER_GEARBOX'


export default {
  ADD_MODEL,
  ADD_ENGINE,
  ADD_GEARBOX,
  ADD_COLOR,
  REMOVE_UNDER_MODEL,
  REMOVE_UNDER_ENGINE,
  REMOVE_UNDER_GEARBOX
}
